### ISSUE TITLE
lezecke lokality sa oznacuju ako strom

### ISSUE THREAD

**Issue by tjamecny** [FreemapSlovakia/freemapSKtopo#1]
(od @Mirecnet)

Zdravim,
vsimol som si, ze v GPS Garmin sa moje lezecke lokality popod skaly oznacuju ako strom.

sport=climbing

V GPS sa zobrazuje strom.
Pozrite sa na to pls.
Dakujem

**Comment by kaylesk** [comment]
Potvrdené. Nie je tam definovaná "naša" ikona, tak použil svoju vlastnú.

**Comment by Mirecnet** [comment]
Dakujem za pozretie a opravu.

**Comment by kaylesk** [comment]
Dnešný update už obsahuje ikony.

**Comment by Mirecnet** [comment]
Potvrdzujem. Je to OK. Dakujem.
