### ISSUE TITLE
Neviditelna polianka v lese

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemapSKtopo#2]
Zdravim,
neviete preco niesu viditelne vsetky polianky v mape pre GPS Garmin ? Je naozaj nutne kazdu malu polianku v kosorevine Chabenca a Prasivej davat do inner  multipoligonu ?
Dnes som mapoval Uhlisko vedla Mosnice a Sinej pri Demanovej. Tuto polianku som v Garmine nevidel.

https://www.openstreetmap.org/way/400657522/history#map=18/49.00013/19.52376

Musel som nacitat mapy.cz a cakat na nacitanie ortomapy na jednej ciarke Edge signalu. Az potom som tam trafil aj napriek tomu, ze na Freemape tato polianka je :)

Jedneho casu bol s tymto problem aj na desktopovom Freemape. Male polianky sa proste nezobrazovali. Neskor to uz bolo OK. Dalo by sa nieco s tym robit aj v GPS pre Garmin ?
Prosim pozrite sa na to.
Dakujem
Miro

**Comment by zdila** [comment]
> Je naozaj nutne kazdu malu polianku v kosorevine Chabenca a Prasivej davat do inner multipoligonu?

Je to nutne. Aj na osm.org ti cez nu kresli stromy co nie je OK.

**Comment by kaylesk** [comment]
Ak sú ako tieto, tak nie sú v relácii a keďže majú rovnaký "draworder" s lesom.
Posuniem ich vyššie, aby boli nad lesné pokrytie.

**Comment by zdila** [comment]
Aj tak to treba dat do relacie, lebo inac to nie je spravne a ine renderery to nemusia vykreslit spravne.

**Comment by Mirecnet** [comment]
Nechcel som kazdu malu polianku 6x6 m davat do inner. Ale budem sa snazit upratat tych par stovak polianok v Tatrach. Za par rokov by sa to malo upratat do multipolygonov.
Dovtedy by bolo dobre, keby sa aspon slabo zobrazili. Nie je nic horsie, ako zabludit v kosodrevine a nevediet, kde je vychod :)
Existuje nejaky rychly efektivny sposob, ako v JOSM dat tuto polianku do inner ? V tomto pripade je multipoligon kto vie kde. Kde vidim, v akom multipolygone sa presne nachadzam ? 
Skusim to od kraja vsetko poopravovat.
Dik za odpoved.
Miro

**Comment by zdila** [comment]
> Existuje nejaky rychly efektivny sposob, ako v JOSM dat tuto polianku do inner?

oznacis nieco co uz v multipolygone je spolu s tym co tam chces dat (Ctrl+click) a stlacis `Ctrl+Shift+B`.
