### ISSUE TITLE
Velkost mapy do Garminu

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/freemapSKtopo#4]
Dnes som si nainstaloval novu mapu do Garminu z http://download.freemap.sk/garmin, kde ma presmerovalo na http://old.freemap.sk/index.php?c=core.download&filename=/garmin

freemapSKtopo.gmapsupp.latin1.zip | 68.41 MB | 21.05.18 09.38

Pozeram, ze povodna mapa mala skoro 200 MB a tato ma len 68 MB v ZIPe.
Je to zmrstene o viac, ako polovicu kapacity mapy.

Nieje to daka chyba ?

**Comment by kaylesk** [comment]
Preverím to.
(Niečo podobné sa stalo aj s "locus mapou". Ale ďalšie spustenie prešlo OK, bez akýchkoľvek zmien.)

**Comment by Mirecnet** [comment]
Prave som si pozrel mapu v GPS a su tam len vrstevnice. 

Mapa komplet chyba :)

Fuuu..mapu potrebujem. Existuje daka zaloha ? Pozeram, ze v sekcii old su len veci v roku 2012.

**Comment by kaylesk** [comment]
Vstupný súbor má nulovú veľkosť, takže sú tam len vrstevnice.

**Comment by kaylesk** [comment]
Bohužiaľ staršia bola zmazaná. Ale už beží nové generovanie. Vstupné dáta stiahlo, takže treba vydržať.

**Comment by Mirecnet** [comment]
Skoda, ze staru verziu v zariadeni som vymazal skor, ako som si to vsimol :(

Dakujem, ze si sa tak promtne na to pozrel a vyriesil problem.

**Comment by kaylesk** [comment]
Už by to malo byť OK.

**Comment by Mirecnet** [comment]
Fuu..to je rychlost :) Cakal som tak 24-48 hodin :D

Odskusane: FUNGUJE

Dakujem za rychle vyriesenie.
