### ISSUE TITLE
Map authentication error with new Garmin GPSMAP 66st

### ISSUE THREAD

**Issue by DiscoverHu** [FreemapSlovakia/freemapSKtopo#5]
Dear All,
I regret to inform you that your Garmin freemapSKtopo map unfortunately does not work on Garmin GPSMAP 66st. The error message is 'The map is closed'. It worked perfectly on Garmin Oregon 650 without any error messages.
Thank you in advance for your help.
Kind regards
Istvan Erdődi
discover.gc@gmail.com
Hungary

**Comment by kaylesk** [comment]
This is know "feature". When Edge 1000 and GPSMap 64 devices come (circa), they stop read UTF maps. Please download map with "latin1" in filename from http://download.freemap.sk/garmin. Maps with and without "latin1" are same, only label charset is different.

**Comment by DiscoverHu** [comment]
Dear Michal,

Thank you for your quick answer and solution.
The 'latin1' map works fine and GPSMAP 66st accepts it without any trouble,

Thank you the perfect free topo map.

Best regards
Istvan Erdodi
Hungary

Michal <notifications@github.com> ezt írta (időpont: 2018. nov. 5., H,
6:26):
